### ISSUE TITLE
[suggestion] (a touch) longer cooldown on the evocator fangs

### ISSUE THREAD

**Issue by majijn** [Lykrast/HarvestersNight#3]
as it currently stands, when the fangs start showing means I must run around until he stops casting them if I was trying to eat instead of getting in position to retaliate against him while casting with my axe/sickle, however sometimes he seems to attack immediately again right after stopping, making sure he cant attack immediately would let the player get to eat a bit more reliably.

LOVING the lil guy btw, he's the only mob that's consistently capable of killing me.
whenever I hear the thunder and that laugh echoing my reaction is always either happiness or fear.
great job on this mood setting mod!

**Comment by majijn** [comment]
I just realised I should probably be using a bow on it while its casting instead of trying to get to melee range ... 
Edit: after fighting him a couple of times, bows does make the fight slightly easier, but it doesnt actually make the fight last less time, meaning eating in between attacks is still an issue.

**Comment by Lykrast** [comment]
Fixed with baedeb27e30de99b31868100138541e8fdfc3d78. There's now a small delay between the laugh and the first claw, and the Harvester stands still for a little more than a second after summoning the last claw.

Should give much easier time to eat if he decides to chain attacks.

**Comment by majijn** [comment]
I was actually about to comment on this again today! made a new world and the first one that spawned successfully managed to kill me because i didnt have a moment to breathe and eat to regen, and now I see this updated hours ago!
so excited to check this out!
