### ISSUE TITLE
the harvester can be trapped 

### ISSUE THREAD

**Issue by majijn** [Lykrast/HarvestersNight#5]
it's not something that bothers me but I just thought you ought to know 
got the idea from seeing this vanilla farm https://youtu.be/Lbi1NbtDNJE
![2019-01-20_05 15 24](https://user-images.githubusercontent.com/18368034/51435378-85526900-1c76-11e9-9af8-3fd066312f6f.png)

**Comment by Lykrast** [comment]
Nice, someone finally found how to cheese him (I didn't know how to either).

I'm perfectly fine with him being cheesable like that, since he's designed to be an early game boss.

**Comment by majijn** [comment]
more cheese: have a platform made of trapdoors and he can't fang you (that or fly when fighting him/edit: or make a deep pond of water)
